[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=7.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# packages = ['decore_base', 'decore_base.classes', 'decore_base.extensions', 'decore_base.library', 'decore_base.prepare', 'decore_base.sample']

